### ISSUE TITLE
What is the database format for information about installed packages?

### ISSUE THREAD

**Issue by techtonik** [megous/spkg#6]
Does spkg use its own database format or injects data into official?

Is there a formal description of formats used? I am looking at how can I reuse the bits for cross-platform packaging in Python.

**Comment by megous** [comment]
The original idea was to use exactly the same format as pkgtools. I remember someone from Salix OS provided some patches that fixed some subtle differences a few years ago. But I'm not sure of the current status. I don't use Slackware anymore.

**Comment by techtonik** [comment]
And what is the format of database used in spkg now? Is it still former format of pkgtools or something different?

**Comment by megous** [comment]
It should be the same. But I'm not sure. There may be subtle differences in spacing. And perhaps Slackware changed the format a bit over the years.

**Comment by techtonik** [comment]
How to check? Basically, I can't start using it, because I don't understand how it works, and if it is safe to use. There is a mention of Windows support, but I don't get what does it mean there. How it cooperates with system metadata storage?

**Comment by megous** [comment]
Just look at the database files generated by slackware pkgtools and by spkg. That's all. They're in a plain text format.

Windows support means spkg can be built on windows. I'm not sure what system metadata storage means. Package database?

**Comment by techtonik** [comment]
Package database, right. There is a lot of posts that you need to use `pkgtools`, but so far no info about how files and their metadata is read, processed and stored. Straight link to the good reference would be really useful.

**Comment by megous** [comment]
I don't understand what you're asking. There's no metadata in package database for installed files in Slackware. Only their name.

**Comment by techtonik** [comment]
And how does Slackware check that some package is installed?

**Comment by megous** [comment]
Here you can read the code: http://packages.slackware.com/?r=slackware-current&p=pkgtools-14.1-noarch-2.tgz

**Comment by techtonik** [comment]
If I could, I didn't question. =) spkg might be an awesome project, ok, but if users have to read the code of pkgtools, then the code of spkg to understand how it works and if they are interoperable, then it just won't work for them.

**Comment by megous** [comment]
If you will not read the code, you'll not be able to reuse anything from spkg.

**Comment by techtonik** [comment]
I see. Not practical for me due to language constraints, but interesting in its own kind due to other reasons. Thanks for the comments, anyway. =)
